### ISSUE TITLE
Bug when 2 bosses are spawned instantly

### ISSUE THREAD

**Issue by JavidPack** [Flashkirby/Yet-Another-Boss-Health-Bar#1]
Use Cheat Sheet or Heros Mod, turn on autopause, spawn 2 bosses, and it'll immediately crash.

The reason for the crash is a "An item with the same key has already been added." exception, presumably a bit of logic is off with your dictionaries.

**Comment by Flashkirby** [comment]
Found reason for issue: all NPCs have a whoAmI Value of 0 when spawned during autopause, causes dictionary entry clashes.

**Comment by Flashkirby** [comment]
Fixed in 70ba1dfd5d2f14d6a5b44f69741b5f576157f213
